### ISSUE TITLE
omitHeader specified globally impacting calls that return only responseHeader like delete_replica

### ISSUE THREAD

**Issue by ralph-tice** [dfdeshom/solrcloudpy#12]
When I invoke something like conn[my_collection].delete_replica(replica,shard) I get a return response like:
```
{}
```
where I expect some formatted version of this (for the successful case) instead:
```
{"responseHeader":{"status":0,"QTime":6022}}
```

It looks like this is because of https://github.com/dfdeshom/solrcloudpy/blob/master/solrcloudpy/utils.py#L36 -- I don't understand why you would ever want to omit the header response, let alone globally for all requests, am I missing something?

Maybe we should make extraparams an argument of _Request.request and default it to just wt:json ?
json.nl=map also seems odd to me to pass on every request.

**Comment by dfdeshom** [comment]
no more feedback given, closing
