### ISSUE TITLE
Null Pointer Exception from application/json header

### ISSUE THREAD

**Issue by relwell** [dfdeshom/solrcloudpy#20]
Working off of the quickstart guide: http://lucene.apache.org/solr/quickstart.html

I've observed the following functionalities work:
1) List collections
2) Create a collection
3) Batch-write to a created collection

The only problem I'm having with this library is actually querying for stored data. This results in the server responding with a null pointer exception.

I found that the source of the problem is this line: https://github.com/dfdeshom/solrcloudpy/blob/master/solrcloudpy/utils.py#L35

When I set the headers variable to be an empty dict, the query works just fine.

Any thoughts on what the problem might be? Similarly, is this header absolutely required? Could we perhaps remove it and bump the version so that I don't have to maintain my own fork?

Thanks!

**Comment by dfdeshom** [comment]
Hi @relwell ,I will try to reproduce your issue with the latest version of Solr. Thanks!

**Comment by dfdeshom** [comment]
Confirmed. Committed a fix here: https://github.com/dfdeshom/solrcloudpy/commit/4c6e8a97b5bddceb4feaeea4bfdd35c691598213 . You can download version `1.6.460`  from pypi t oget the fix

**Comment by relwell** [comment]
Thanks!
